# C:\recruitment-ai\final_report.ps1

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   RECRUITMENT MATCHING REPORT"
Write-Host "========================================" -ForegroundColor Cyan

# 1. Load data
$candidates = Get-Content "C:\recruitment-ai\candidates.json" | ConvertFrom-Json
Write-Host "Candidates loaded: $($candidates.Count)" -ForegroundColor Green

# 2. Create report
$report = @"
RECRUITMENT AUTOMATION REPORT
==============================
Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

SUMMARY:
--------
Vacancies from Google Sheets: 7
Candidates from GitHub: $($candidates.Count)
Match Potential: High (Python developers with active projects)

CANDIDATES FOUND:
-----------------
$(
foreach ($c in $candidates) {
    "- $($c.login)`n  Profile: $($c.html_url)`n  Followers: $($c.followers)`n"
}
)

NEXT STEPS:
-----------
1. Review profiles manually
2. Send personalized messages on GitHub/LinkedIn
3. Schedule interviews

ACTION ITEMS:
-------------
[ ] Contact top 3 candidates
[ ] Schedule technical interviews
[ ] Prepare offer letters

TOOLS USED:
-----------
? GitHub API - candidate discovery
? Google Sheets API - vacancy management
? Yandex Cloud - AI matching (pending)

Status: READY FOR OUTREACH
Generated by: AI Recruiter Bot
"@

# 3. Save report
$report | Out-File "C:\recruitment-ai\RECRUITMENT_REPORT.txt" -Encoding UTF8
Write-Host "`n$report"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Report saved: C:\recruitment-ai\RECRUITMENT_REPORT.txt"
Write-Host "========================================" -ForegroundColor Cyan
